### PR TITLE
Complete rewrite

### PR DESCRIPTION
**Pull request by jkuhl-dev**
## Changes
- Complete rewrite to improve stability, code quality, and maintainability. This should also allow this to run on any x86_64 Linux system capable of installing Python
- Removed built in update functionality, updates should be handled by the system's package manager
- Removed auto start functionality, this can be reimplemented as a systemd service in the future

### CODE REVIEW

**Comment by powenn** [comment]
Action check failed

**Comment by jkuhl-dev** [comment]
> Action check failed

Whoops, fixed the Ubuntu build script!

**Comment by powenn** [comment]
I will check later

**Comment by powenn** [comment]
I would prefer merging it into a new branch "rewrite" after check,would you mind that?

**Comment by jkuhl-dev** [comment]
> I would prefer merging it into a new branch "rewrite" after check,would you mind that?

Sure that's fine. Deb generation should be working now, I just tested out the .deb on an Ubuntu host.

**Comment by powenn** [comment]
> > I would prefer merging it into a new branch "rewrite" after check,would you mind that?
> 
> Sure that's fine. Deb generation should be working now, I just tested out the .deb on an Ubuntu host.

I am testing it and found some problems
- Notification after installation first time missed
- Update option only update binary and ipa,but what if we need to update GUI itself

**Comment by jkuhl-dev** [comment]
>     * Notification after installation first time missed

Can you elaborate on what this is so I can look into it?

>     * Update option only update binary and ipa,but what if we need to update GUI itself

The GUI package should be updated by the system's package manager, for Ubuntu this would be apt. We can create a [PPA](https://help.ubuntu.com/community/PPA) to allow for easy installation and updating of the GUI package on Ubuntu. There are similar options available for other distros such as the [AUR](https://aur.archlinux.org/) for Arch, the [OpenSuse Build Service](http://en.opensuse.org//openSUSE:Build_Service) which supports several distros, [Copr](https://copr.fedorainfracloud.org/) for Fedora, etc.

**Comment by powenn** [comment]
There is no installtion successed notification after first time install Altstore( you can try with delete AltServerData folder)
But that's not a serious problem,so we can just ignore it currently,not emergency
I almost check the whole code ,and i like this,would you keep working on improving this ?

**Comment by jkuhl-dev** [comment]
> There is no installtion successed notification after first time install Altstore( you can try with delete AltServerData folder) I almost check the whole code ,and i like this,would you keep working on improving this ?

Ahh gotcha, yeah I don't think I implemented that. I can work on adding that notification back in sometime in the next few days. And sure yeah I'd love to work on improving this!

**Comment by powenn** [comment]
> > There is no installtion successed notification after first time install Altstore( you can try with delete AltServerData folder) I almost check the whole code ,and i like this,would you keep working on improving this ?
> 
> Ahh gotcha, yeah I don't think I implemented that. I can work on adding that notification back in sometime in the next few days. And sure yeah I'd love to work on improving this!

Nice,thanks for contributing this project

**Comment by powenn** [comment]
New problem founded:
- While run as installed app ,
 Alert: Installation Failed
boost::filesystem::create_directory: Permission denied: "./AltServerData"

But run in terminal or vscode don't have this problem
- In terminal 
  File "main.py", line 569, in gui_quit
NameError: name 'exit' is not defined
Aborted (core dumped)

**Comment by jkuhl-dev** [comment]
>       File "main.py", line 569, in gui_quit
>       NameError: name 'exit' is not defined
>       Aborted (core dumped)

Line 569 is: `exit(0)`. Not sure why this wouldn't be defined given that exit() is a core part of Python. I'll look into this and the other stuff this week.

**Comment by jkuhl-dev** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4448

Looks like this is a known issue with Pyinstaller, should be easy to fix.

**Comment by powenn** [comment]
boost::filesystem::create_directory: Permission denied: "./AltServerData"

AltServerData folder was created in path  /usr/lib/altserver-gui which the app binary placed in
But since without root access ,It can't be create
And that's why I use postinst before

So here is the currecnt solution 

https://github.com/powenn/AltServer-LinuxGUI/commit/b9b7e240fc7b3d22bdd2c34235d8d0e98c330929

And we also need a notification that telling users update finished

**Comment by powenn** [comment]
Update:
Fixed AltServerData folder problem,Now it will be created in $HOME,so won't require root permission

Now trying add auto start and improve update option(I might use json to storage version info includes AltServer,AltStore,App itself

**Comment by jkuhl-dev** [comment]
For the auto start we just need to create a systemd service file which would be included in the deb package skeleton.

https://www.freedesktop.org/software/systemd/man/systemd.service.html
https://askubuntu.com/questions/876733/where-are-the-systemd-units-services-located-in-ubuntu

Below is a systemd service I wrote for a small script I use for managing WireGuard connection on my computer, we can use this as a template for this project.

py_wgm.service
```
[Unit]
Description=Python WireGuard Manager
After=network-online.target nss-lookup.target
Wants=network-online.target nss-lookup.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/etc/PyWireGuardManager/py_wgm start
ExecStop=/usr/local/etc/PyWireGuardManager/py_wgm stop
ExecReload=/usr/local/etc/PyWireGuardManager/py_wgm start

[Install]
WantedBy=multi-user.target
```

**Pull request merged**
